# Generated by Django 3.2.4 on 2021-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
