# Generated by Django 3.2.4 on 2021-06-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
            preserve_default=False,
        ),
    ]
