# Generated by Django 3.2.4 on 2021-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.CharField(max_length=14, null=True),
        ),
    ]
