# Generated by Django 3.2.4 on 2021-06-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_transaction_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_time",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(default=""),
            preserve_default=False,
        ),
    ]
