# Generated by Django 3.2.4 on 2021-06-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20210619_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(auto_now=True),
        ),
    ]
