# Generated by Django 3.2.4 on 2021-06-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_transaction_transaction_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_date",
        ),
    ]
