# Generated by Django 3.2.4 on 2021-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_transaction_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(default="2021-06-19"),
        ),
    ]
