# Generated by Django 3.2.4 on 2021-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_transaction_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(auto_now=True),
        ),
    ]
